#!/bin/bash

OPTSTRING=":aV:rV:hv"
VERSION="0.0.1"

#check for root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

while getopts $OPTSTRING opt; do
    case $opt in
        a)
            echo $OPTARG >> 
