#!/bin/bash

VERSION="0.0.1"

#check for root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

#option for adding a package with no version
if [ $0 == "-a" ]; then
    echo $1 " 0.0" >> /var/lib/soupy/list
    echo "Added " $1 " 0.0"
fi

#option for adding a package with version
if [ $0 == "-a" && $2 == "-v" ]; then
    echo $1 " " $3 >> /var/lib/soupy/list
    echo "Added " $1 " " $3
fi

#option for giving version number
if [ $0 == "-V" || $0 == "-v" ]; then
    echo $VERSION
fi

